ALTER TABLE USER_APPLICATION
ALTER COLUMN firstName TYPE VARCHAR,
ALTER COLUMN lastName TYPE VARCHAR,
ALTER COLUMN username TYPE VARCHAR,
ALTER COLUMN profileImage TYPE VARCHAR,
ALTER COLUMN email TYPE VARCHAR;